name: Render deployment

on:
  workflow_dispatch

jobs:
  Render-Deployment:
      runs-on: ubuntu-latest
      steps:
        - name: Render deployment
          env:
            deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl $deploy_url
